config/routes.rb
Cards::Application.routes.draw do
  resources :entries

  resources :octopi

  resources :playas

  resources :black_cards

  resources :white_cards

end

app/models/playa.rb
class Playa < ActiveRecord::Base
  attr_accessible :bling, :email
end

app/controllers/playas_controller.rb
class PlayasController < ApplicationController
  # GET /playas
  # GET /playas.json
  def index
    @playas = Playa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @playas }
    end
  end

  # GET /playas/1
  # GET /playas/1.json
  def show
    @playa = Playa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playa }
    end
  end

  # GET /playas/new
  # GET /playas/new.json
  def new
    @playa = Playa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playa }
    end
  end

  # GET /playas/1/edit
  def edit
    @playa = Playa.find(params[:id])
  end

  # POST /playas
  # POST /playas.json
  def create
    @playa = Playa.new(params[:playa])

    respond_to do |format|
      if @playa.save
        format.html { redirect_to @playa, notice: 'Playa was successfully created.' }
        format.json { render json: @playa, status: :created, location: @playa }
      else
        format.html { render action: "new" }
        format.json { render json: @playa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playas/1
  # PUT /playas/1.json
  def update
    @playa = Playa.find(params[:id])

    respond_to do |format|
      if @playa.update_attributes(params[:playa])
        format.html { redirect_to @playa, notice: 'Playa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playas/1
  # DELETE /playas/1.json
  def destroy
    @playa = Playa.find(params[:id])
    @playa.destroy

    respond_to do |format|
      format.html { redirect_to playas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/playas_helper.rb
module PlayasHelper
end

app/views/playas/_form.html.erb
<%= form_for(@playa) do |f| %>
  <% if @playa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playa.errors.count, "error") %> prohibited this playa from being saved:</h2>

      <ul>
      <% @playa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :bling %><br />
    <%= f.text_field :bling %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playas/edit.html.erb
<h1>Editing playa</h1>

<%= render 'form' %>

<%= link_to 'Show', @playa %> |
<%= link_to 'Back', playas_path %>

app/views/playas/index.html.erb
<h1>Listing playas</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Bling</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @playas.each do |playa| %>
  <tr>
    <td><%= playa.email %></td>
    <td><%= playa.bling %></td>
    <td><%= link_to 'Show', playa %></td>
    <td><%= link_to 'Edit', edit_playa_path(playa) %></td>
    <td><%= link_to 'Destroy', playa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Playa', new_playa_path %>

app/views/playas/new.html.erb
<h1>New playa</h1>

<%= render 'form' %>

<%= link_to 'Back', playas_path %>

app/views/playas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @playa.email %>
</p>

<p>
  <b>Bling:</b>
  <%= @playa.bling %>
</p>


<%= link_to 'Edit', edit_playa_path(@playa) %> |
<%= link_to 'Back', playas_path %>