config/routes.rb
Cards::Application.routes.draw do
  resources :entries

  resources :octopi

  resources :playas

  resources :black_cards

  resources :white_cards

end

app/models/black_card.rb
class BlackCard < ActiveRecord::Base
  attr_accessible :blanks, :text
end

app/controllers/black_cards_controller.rb
class BlackCardsController < ApplicationController
  # GET /black_cards
  # GET /black_cards.json
  def index
    @black_cards = BlackCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @black_cards }
    end
  end

  # GET /black_cards/1
  # GET /black_cards/1.json
  def show
    @black_card = BlackCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @black_card }
    end
  end

  # GET /black_cards/new
  # GET /black_cards/new.json
  def new
    @black_card = BlackCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @black_card }
    end
  end

  # GET /black_cards/1/edit
  def edit
    @black_card = BlackCard.find(params[:id])
  end

  # POST /black_cards
  # POST /black_cards.json
  def create
    @black_card = BlackCard.new(params[:black_card])

    respond_to do |format|
      if @black_card.save
        format.html { redirect_to @black_card, notice: 'Black card was successfully created.' }
        format.json { render json: @black_card, status: :created, location: @black_card }
      else
        format.html { render action: "new" }
        format.json { render json: @black_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /black_cards/1
  # PUT /black_cards/1.json
  def update
    @black_card = BlackCard.find(params[:id])

    respond_to do |format|
      if @black_card.update_attributes(params[:black_card])
        format.html { redirect_to @black_card, notice: 'Black card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @black_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /black_cards/1
  # DELETE /black_cards/1.json
  def destroy
    @black_card = BlackCard.find(params[:id])
    @black_card.destroy

    respond_to do |format|
      format.html { redirect_to black_cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/black_cards_helper.rb
module BlackCardsHelper
end

app/views/black_cards/_form.html.erb
<%= form_for(@black_card) do |f| %>
  <% if @black_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@black_card.errors.count, "error") %> prohibited this black_card from being saved:</h2>

      <ul>
      <% @black_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blanks %><br />
    <%= f.number_field :blanks %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/black_cards/edit.html.erb
<h1>Editing black_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @black_card %> |
<%= link_to 'Back', black_cards_path %>

app/views/black_cards/index.html.erb
<h1>Listing black_cards</h1>

<table>
  <tr>
    <th>Blanks</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @black_cards.each do |black_card| %>
  <tr>
    <td><%= black_card.blanks %></td>
    <td><%= black_card.text %></td>
    <td><%= link_to 'Show', black_card %></td>
    <td><%= link_to 'Edit', edit_black_card_path(black_card) %></td>
    <td><%= link_to 'Destroy', black_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Black card', new_black_card_path %>

app/views/black_cards/new.html.erb
<h1>New black_card</h1>

<%= render 'form' %>

<%= link_to 'Back', black_cards_path %>

app/views/black_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Blanks:</b>
  <%= @black_card.blanks %>
</p>

<p>
  <b>Text:</b>
  <%= @black_card.text %>
</p>


<%= link_to 'Edit', edit_black_card_path(@black_card) %> |
<%= link_to 'Back', black_cards_path %>