config/routes.rb
Cards::Application.routes.draw do
  resources :entries

  resources :octopi

  resources :playas

  resources :black_cards

  resources :white_cards

end

app/models/white_card.rb
class WhiteCard < ActiveRecord::Base
  attr_accessible :text
end

app/controllers/white_cards_controller.rb
class WhiteCardsController < ApplicationController
  # GET /white_cards
  # GET /white_cards.json
  def index
    @white_cards = WhiteCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @white_cards }
    end
  end

  # GET /white_cards/1
  # GET /white_cards/1.json
  def show
    @white_card = WhiteCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @white_card }
    end
  end

  # GET /white_cards/new
  # GET /white_cards/new.json
  def new
    @white_card = WhiteCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @white_card }
    end
  end

  # GET /white_cards/1/edit
  def edit
    @white_card = WhiteCard.find(params[:id])
  end

  # POST /white_cards
  # POST /white_cards.json
  def create
    @white_card = WhiteCard.new(params[:white_card])

    respond_to do |format|
      if @white_card.save
        format.html { redirect_to @white_card, notice: 'White card was successfully created.' }
        format.json { render json: @white_card, status: :created, location: @white_card }
      else
        format.html { render action: "new" }
        format.json { render json: @white_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /white_cards/1
  # PUT /white_cards/1.json
  def update
    @white_card = WhiteCard.find(params[:id])

    respond_to do |format|
      if @white_card.update_attributes(params[:white_card])
        format.html { redirect_to @white_card, notice: 'White card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @white_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /white_cards/1
  # DELETE /white_cards/1.json
  def destroy
    @white_card = WhiteCard.find(params[:id])
    @white_card.destroy

    respond_to do |format|
      format.html { redirect_to white_cards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/white_cards_helper.rb
module WhiteCardsHelper
end

app/views/white_cards/_form.html.erb
<%= form_for(@white_card) do |f| %>
  <% if @white_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@white_card.errors.count, "error") %> prohibited this white_card from being saved:</h2>

      <ul>
      <% @white_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/white_cards/edit.html.erb
<h1>Editing white_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @white_card %> |
<%= link_to 'Back', white_cards_path %>

app/views/white_cards/index.html.erb
<h1>Listing white_cards</h1>

<table>
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @white_cards.each do |white_card| %>
  <tr>
    <td><%= white_card.text %></td>
    <td><%= link_to 'Show', white_card %></td>
    <td><%= link_to 'Edit', edit_white_card_path(white_card) %></td>
    <td><%= link_to 'Destroy', white_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New White card', new_white_card_path %>

app/views/white_cards/new.html.erb
<h1>New white_card</h1>

<%= render 'form' %>

<%= link_to 'Back', white_cards_path %>

app/views/white_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @white_card.text %>
</p>


<%= link_to 'Edit', edit_white_card_path(@white_card) %> |
<%= link_to 'Back', white_cards_path %>